on:
  push:
    branches:
      - main
  pull_request:

name: Cargo Format

jobs:
  fmt:
    name: Cargo Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt --all -- --check
